# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Congo < Formula
  desc "Easy and unified way to connect from your terminal to AWS EC2 and ECS"
  homepage "https://github.com/PauSabatesC/congo"
  version "0.1.1"
  license "Apache 2.0 license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PauSabatesC/congo/releases/download/v0.1.1/congo_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "db50d36492d573ca4a86f5250b35c6da326baa44c6a888df46ff611c3320786e"

      def install
        bin.install "congo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PauSabatesC/congo/releases/download/v0.1.1/congo_0.1.1_Darwin_arm64.tar.gz"
      sha256 "5279b0f4ec023699ad210387ef8d095c36ad9c8a1b275886f7e1cb8075a2e070"

      def install
        bin.install "congo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/PauSabatesC/congo/releases/download/v0.1.1/congo_0.1.1_Linux_armv6.tar.gz"
      sha256 "b29c88c3dd05fbcb45b5c8831fc951f623a9ede9a2db01d150170c7473aa4d48"

      def install
        bin.install "congo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PauSabatesC/congo/releases/download/v0.1.1/congo_0.1.1_Linux_arm64.tar.gz"
      sha256 "bde683053fcb1af5e7f3ffc6d17a421f4cc736982c2cdeb6443fa3b344da1930"

      def install
        bin.install "congo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/PauSabatesC/congo/releases/download/v0.1.1/congo_0.1.1_Linux_x86_64.tar.gz"
      sha256 "40182452051228ac427a085d90eb8eecdc0f29063c67aad22afd59728e89f66b"

      def install
        bin.install "congo"
      end
    end
  end
end
